version: '2'
services:
  odoo:
    image: odoo:16
    ports:
      - "7496:8069"
      - "0323:8072"
    tty: true
    command: odoo
    volumes:
      - data:/var/lib/odoo
      - ./custom_modules:/mnt/extra-addons
      - ./etc:/etc/odoo
  db:
    image: postgres:11
    command: postgres -c 'max_connections=300'
    ports:
      - "6712:5432"
    environment:
      - POSTGRES_PASSWORD=gaweanCintaAllah123!
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
volumes:
  data:
  postgresql: